# General Configuration
# REMOVED: device: "cuda"
# ADDED: device_ids list to control GPU usage
device_ids: [0, 1]  # Use GPUs 0 and 1. For single GPU, use [0] or [1].
seed: 42
num_workers: 4

# Data Configuration
dataset:
  name: "cifar10"
  path: "./datasets/cifar10"
  img_size: 32
  num_classes: 10

# Model Configuration
surrogate_model:
  name: "resnet18"
  pretrained_path: "./pretrained/resnet18_cifar10.pth"
victim_model:
  name: "resnet18"

# LFDA-U Trigger Generator Training Configuration (using the high-ASR config)
generator_training:
  epochs: 100
  batch_size: 128
  lr: 0.001
  target_class: 0

  lambda_latent: 1.0
  lambda_stealth_mse: 10.0
  lambda_stealth_lpips: 5.0
  lambda_smooth: 0.001

  save_dir: "./checkpoints/generator"
  save_name: "generator_cifar10_v4.pth"

# Victim Model Training Configuration
victim_training:
  generator_path: "./checkpoints/generator/generator_cifar10_v4.pth"
  epochs: 100
  batch_size: 128
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

  attack_type: "clean_label"
  poison_rate: 0.1
  target_class: 0

  eval_every_epochs: 5

  save_dir: "./checkpoints/victim_model"
  save_name: "victim_resnet18_cifar10.pth"

# Evaluation Configuration
evaluation:
  victim_model_path: "./checkpoints/victim_model/victim_resnet18_cifar10.pth"
  generator_path: "./checkpoints/generator/generator_cifar10_v4.pth"
  batch_size: 256