# =================================================================================================
# configs/cifar10_advanced_joint.yml (GPU配置版)
# =================================================================================================
# General settings
log_dir: 'logs/adversarial_colearning'
model_dir: 'checkpoints/adversarial_colearning'

# Dataset settings
dataset:
  name: 'CIFAR10'
  root_dir: '~/home/machao/pythonproject/lfda/datasets/cifar10'
  num_classes: 10
  batch_size: 1024
  num_workers: 4

# Model settings
# victim_model and generator are created from scratch
# teacher_model is loaded from a pre-trained path
teacher_model_path: 'checkpoints/clean_model/classifier_epoch_100.pth' # 重要：请确保此路径有预训练好的干净模型

# Optimizer settings
optimizer:
  lr_F: 0.001       # Learning rate for victim_model
  lr_G: 0.001       # Learning rate for generator
  beta1: 0.5
  beta2: 0.999

# Training settings
train:
  max_epochs: 100
  # --- GPU配置选项 ---
  # 在这里指定要使用的GPU ID。
  # 单GPU示例: '0'
  # 双GPU示例: '0,1'
  gpu_ids: '0,1'

# Attack settings
attack:
  target_class_idx: 0
  poisoning_ratio: 1.0  # 用于 victim_model 训练时，目标类中毒的比例
  magnitude: 40.0
  yf_thresh: 30.0

  # --- 复合损失权重 ---
  lambda_learnability: 1.5      # 后门可学习性损失权重 (victim_model)
  lambda_transferability: 0.5   # 对抗性迁移损失权重 (teacher_model)

  # 其他损失权重保持不变
  lambda_feat: 0.5              # 特征保持损失（可选，可以设为0来简化）
  lambda_stealth_lpips: 5.0     # 视觉隐蔽性损失权重