# General Configuration
device_ids: [0]
seed: 42
num_workers: 4

# Data Configuration
dataset:
  name: "cifar10"
  path: "./datasets/cifar10"
  img_size: 32
  num_classes: 10

# Model Configuration
model:
  name: "resnet18"

# --- 联合端到端训练配置 (高级版) ---
joint_training:
  epochs: 100
  batch_size: 1024
  target_class: 0

  poison_ratio_in_batch: 0.5

  # Optimizers
  optimizer_F:
    type: "SGD"
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
  optimizer_G:
    type: "Adam"
    lr: 0.001

  # Loss weights
  lambda_attack: 2.0
  lambda_stealth_lpips: 5.0
  lambda_feat: 0.5

  # 升级的训练策略参数
  weak_trigger_strength: 0.3  # 训练时使用的基础强度
  strong_trigger_strength: 0.8 # 评估时使用的基础强度

  # Save & Eval Configuration
  eval_every_epochs: 10
  save_dir: "./checkpoints/advanced_joint"
  generator_save_name: "generator_final_adv.pth"
  classifier_save_name: "classifier_final_adv.pth"

# --- 最终评估配置 ---
evaluation:
  victim_model_path: "./checkpoints/advanced_joint/classifier_final_adv.pth"
  generator_path: "./checkpoints/advanced_joint/generator_final_adv.pth"
  batch_size: 1024